### ISSUE TITLE
Create New Project: Choose Your Scenario

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/hidraulica-disseny#1]
It was this option?

![image](https://cloud.githubusercontent.com/assets/12971681/13178808/2cb1c5f4-d721-11e5-87bd-1be914b32ace.png)

**Comment by davidromani** [comment]
It dependes on how you start the initial code...

I recommend to start a new fresh symfony 2.8 instalation (check symfony doc. before), and then tell PHPStorm that you want to manage a local project (last option)
