### ISSUE TITLE
Troubles with composer

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/hidraulica-disseny#8]
After update all the branches, I did a composer install and crashed into the Sonata Admin Bundle ?¿

![image](https://cloud.githubusercontent.com/assets/12971681/15520674/c7b34394-2207-11e6-8e4e-db223b4fd2c0.png)

**Comment by davidromani** [comment]
do it again (composer install), sometimes is really anoying

**Comment by aserratorta** [comment]
good! it works.
